sudo: required
services:
  - docker

# command to run tests
script: bash ./run_tests.sh

notifications:
  email:
    recipients:
      - peter.vorman@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
