sudo: required
services:
  - docker
before_install:
  - docker-compose up -d mongodb
language: python

python:
  - "3.4"
  - "3.5"

# command to install dependencies
install: 
  - pip install -e .
  - pip install coveralls

# command to run tests
script: bash ./run_tests.sh

after_success:
  coveralls

notifications:
  email:
    recipients:
      - peter.vorman@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
