version: "3"

services:
  dev:
    container_name: dev_container
    image: dev_container
    working_dir: /opt
    environment:
      - COVERALLS_REPO_TOKEN=UdEu7TxCBgJxLNLCy3T1GzTBRwuopI473
    build:
      context: ./dockerfiles/dev_container
    volumes:
      - ./:/opt
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
     - front
     - backend
     - db
    ports:
      - "222:22"

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./mongo_data:/data/db
    networks:
     - db
    ports:
      - "27017:27017"

  mongodbclient:
    container_name: mongodbclient
    image: mongoclient/mongoclient:latest
    networks:
     - front
     - backend
     - db
    ports:
      - "3000:3000"
    links:
      - mongodb:mongodb

networks:
  front:
  backend:
  db: